# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fb2d58f3f87091fecc36841377d7b2382bb946dde2e4b1b6ad7e9387fe7a98bc06ae4af2f3f30da611ed46243a56d37b49379cc23bfde0b940bee923de7ef46

test:
  secret_key_base: b21991f64303e2e9afe3ebf12112519be3914400911e1e1c01a762a45084dac128461408a54b74d2a311c70f016dadf6f79c8e9c4f892322e66a47d6851407a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
